[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

# [profile.default]
# via-ir = true # Enable the IR-based optimizer (yul)
# optimizer = true
# optimizer_runs = 10_000
# bytecode_hash = "none" # pr